### ISSUE TITLE
PlatformException - Failed to generate key pair

### ISSUE THREAD

**Issue by batuhanseckinnn** [BreX900/mek-packages#47]
Thanks for the great package!

I developed a simple demo app using this plugin. But while it works fine on Android 12 and above devices, I get the following error on an Android 11 device.

`Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, Failed to generate key pair, null, java.security.ProviderException: Failed to generate key pair
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:515)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:471)
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
	at java.security.KeyPairGenerator.genKeyPair(KeyPairGenerator.java:497)
	at com.stripe.cots.common.compatibility.PreFlightChecks.initialize(Unknown Source:87)
	at com.stripe.stripeterminal.internal.common.adapter.CotsClient.initializeKeys(Unknown Source:2)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.initKeystore(Unknown Source:2)
	at com.stripe.stripeterminal.Terminal$Companion.initTerminal(SourceFile:3)
	at com.stripe.stripeterminal.Terminal$Companion.initTerminal(SourceFile:2)
	at s6.c.g(Unknown Source:109)
	at t6.m1$b.b(Unknown Source:393)
	at t6.m1$b.a(Unknown Source:0)
	at t6.l1.a(Unknown Source:2)
	at k4.j$a.a(Unknown Source:17)
	at c4.c.l(Unknown Source:18)
	at c4.c.m(Unknown Source:40)
	at c4.c.i(Unknown Source:0)
	at c4.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7664)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.security.KeyStoreException: Unknown error
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
	... 25 more
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:651)
       at MethodChannel._invokeMethod(platform_channel.dart:322)
       at _$TerminalPlatform.init(terminal_platform.api.dart:27)
       at Terminal.getInstance.<fn>(terminal.dart:52)
       at _HomeViewState._initTerminal(home.dart:102)`
       
       
Device informations

<img width="962" alt="Screenshot 2023-12-27 at 12 57 25" src="https://github.com/BreX900/mek-packages/assets/139364224/1405c082-74c3-4252-9e31-a2f98a32e454">

### pubspec.yaml 

```name: mek_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mek_stripe_terminal: ^3.2.0
  stripe:
    git:
      url: https://github.com/enyo/stripe-dart
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
```

### project/build.gradle

```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.1.3'
        // START: FlutterFire Configuration
        classpath 'com.google.gms:google-services:4.4.0'
        // END: FlutterFire Configuration
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
```

### project/app/build.gradle 

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
// END: FlutterFire Configuration
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdk 34 // flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.companyname.mek_test.mek_test"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
        minSdkVersion 26
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
    namespace 'com.companyname.mek_test.mek_test'
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

Flutter version: 3.16.0 (stable channel)
mek_stripe_terminal: ^3.2.0

I would like to know if there are any suggestions or updates to resolve this issue. I'm also wondering if other users are experiencing this issue and if there is a potential workaround.

**Comment by BreX900** [comment]
Hi, it doesn't seem to be a problem with my library but a problem with the native sdk.
I upgraded my library to version 3.2.1 to support the latest version of native sdk 3.2.1. Please try this version otherwise I suggest you open an issue on the native sdk

**Comment by batuhanseckinnn** [comment]
I cloned this plugin to my computer and changed the following lines:

**stripe_terminal/android/build.gradle**

```
api "com.stripe:stripeterminal-localmobile:3.2.1"
api "com.stripe:stripeterminal-core:3.2.1"
```

to

```
implementation "com.stripe:stripeterminal:3.1.1"
```

I'm not experiencing any problems right now. init, discover, connect etc are working.

I do not intend to use the tap to pay feature, and if I understand correctly, some devices give errors when we try to offer this as an extra feature. Did I understand correctly?

**Comment by BreX900** [comment]
Yes, those packages are for tap to pay. If you don't use it you can easily set everything as you did.
I would be curious to know if it gives you problems if you set:
```
api "com.stripe:stripeterminal-localmobile:3.2.1"
api "com.stripe:stripeterminal-core:3.2.1"
```
or
```
implementation "com.stripe:stripeterminal:3.2.1"
```

Maybe the problem is that `api` is used and not `implementation` or if the problem is with the latest version

**Comment by batuhanseckinnn** [comment]
Thank you for your attention to the issue.

```
implementation "com.stripe:stripeterminal-localmobile:3.2.1"
implementation "com.stripe:stripeterminal-core:3.2.1"
```
When attempting this approach, I continue to encounter the same error:

``` PlatformException(error, Failed to generate key pair, ... ```

---

``` 
implementation "com.stripe:stripeterminal:3.2.1" 
```

Using this configuration results in a different error:

``` stripe Terminal Exception: Offline mode is not available on this device ```

---

After encountering the "offline mode" error, I conducted some research. According to [Stripe's documentation](https://stripe.com/docs/terminal/features/operate-offline/collect-payments?terminal-sdk-platform=android&reader-type=bluetooth#enable-offline-mode), versions 3.2.0 or newer are required to enable offline mode.

Therefore, I decided to test the version immediately preceding 3.2.0. 
Implementing version 3.1.1 seems to have resolved the issue for me.

``` implementation "com.stripe:stripeterminal:3.1.1" ```


However, this feels like a temporary solution to me. Even if I don't plan to use features like tap-to-pay or offline mode, I should still be able to use the latest version. If I'm not mistaken, Stripe provides support up to Android 8.

If you need more information I can share it. I can also share my project codes. After all, as I said, this is a demo app.

**Comment by BreX900** [comment]
Truly strange. I will leave this issue open for a while in case someone experiences the same problem as you or finds a solution. Thank you very much

**Comment by batuhanseckinnnn** [comment]
I am having problems because the device I am using does not meet these requirements.

https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=android#supported-devices
