### ISSUE TITLE
Invalid Required Parameter of iOS when trying to collectionPaymentMethod on (via Mobile Reader)

### ISSUE THREAD

**Issue by StephanWalters** [BreX900/mek-packages#61]
I am getting an invalidateRequiredParameter error on the Terminal.collectPaymentMethod() only on **iOS**.

Android is working as expected.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: TerminalException: invalidRequiredParameter
A required parameter was invalid or missing.
#0      TerminalPlatform._throwIfIsHostException (package:mek_stripe_terminal/src/platform/terminal_platform.dart:185:5)
#1      _$TerminalPlatform.startCollectPaymentMethod (package:mek_stripe_terminal/src/platform/terminal_platform.api.dart:288:24)
<asynchronous suspension>
#2      Terminal.collectPaymentMethod.<anonymous closure> (package:mek_stripe_terminal/src/terminal.dart:331:14)
```

This is the payment intent i am creating server side. and this is the response I'm getting from Stripe.

```
{
  "object": {
    "id": "pi_xxxxxx",
    "object": "payment_intent",
    "amount": 2120,
    "amount_capturable": 0,
    "amount_details": {
      "tip": {
      }
    },
    "amount_received": 0,
    "application": null,
    "application_fee_amount": null,
    "automatic_payment_methods": {
      "enabled": false
    },
    "canceled_at": null,
    "cancellation_reason": null,
    "capture_method": "automatic",
    "client_secret": "pi_xxxxxxxx",
    "confirmation_method": "automatic",
    "created": 1711836594,
    "currency": "usd",
    "customer": null,
    "description": null,
    "invoice": null,
    "last_payment_error": null,
    "latest_charge": null,
    "livemode": false,
    "metadata": {
      "buyerId": "terminal",
    },
    "next_action": null,
    "on_behalf_of": "acct_1xxxxxxxxx",
    "payment_method": null,
    "payment_method_configuration_details": null,
    "payment_method_options": {
      "card_present": {
        "request_extended_authorization": false,
        "request_incremental_authorization_support": false
      }
    },
    "payment_method_types": [
      "card_present"
    ],
    "processing": null,
    "receipt_email": null,
    "review": null,
    "setup_future_usage": null,
    "shipping": null,
    "source": null,
    "statement_descriptor": null,
    "statement_descriptor_suffix": null,
    "status": "requires_payment_method",
    "transfer_data": {
      "destination": "acct_xxxx"
    },
    "transfer_group": null
  }
}
```

**Comment by StephanWalters** [comment]
Closing as not an issue with the SDK using `on_behalf_of` is marked as an invalid parameter some how for  iOS, but seems to work on Android when creating the payment intent server side.
